sudo: false
dist: trusty
language: node_js

cache:
  directories:
    - node_modules

sudo: required

addons:
  chrome: stable

node_js:
  - "lts/*"

matrix:
  fast_finish: true

install:
  - npm install

after_install:
  - ./node_modules/protractor/bin/webdriver-manager update

script:
  - npm test
