sudo: false
dist: trusty
language: node_js

cache:
  directories:
    - node_modules

sudo: required

addons:
  chrome: stable

node_js:
  - "lts/*"

matrix:
  fast_finish: true

before_install:
  - npm cache verify
  - npm prune
  - npm update

install:
  - npm install

after_install:
  - ./node_modules/protractor/bin/webdriver-manager update

script:
  - npm test
